name: Balto (Javascript)

on: [pull_request]

jobs:
  lint_javascript:
    name: Lint JS
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - uses: alexandervalencia/balto-eslint@fix-eslint
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
